# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-05 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='user_permission',
        ),
        migrations.AddField(
            model_name='permission',
            name='role_permission',
            field=models.CharField(max_length=32, null=True, verbose_name='角色权限'),
        ),
    ]
