# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20181105_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='action',
        ),
        migrations.AddField(
            model_name='role',
            name='action',
            field=models.BooleanField(default=False, verbose_name='是否授权'),
        ),
    ]
