# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-01 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linkman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.BooleanField(verbose_name='性别')),
                ('duty', models.CharField(max_length=10, verbose_name='职务')),
                ('phone', models.IntegerField(verbose_name='手机')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('QQ', models.IntegerField(verbose_name='QQ')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='地址')),
                ('link_important', models.CharField(max_length=10, verbose_name='重要等级')),
                ('following', models.CharField(max_length=10, verbose_name='跟进状态')),
                ('link_agent', models.CharField(max_length=20, verbose_name='经办人')),
                ('is_accept', models.BooleanField(verbose_name='是否认可')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('org_address', models.CharField(max_length=100, verbose_name='机构地址')),
                ('mobile', models.IntegerField(verbose_name='手机')),
                ('tel', models.IntegerField(verbose_name='电话')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='国家')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('postcode', models.CharField(blank=True, max_length=6, null=True, verbose_name='邮编')),
                ('site', models.CharField(blank=True, max_length=50, null=True, verbose_name='网站')),
                ('industry', models.CharField(max_length=10, verbose_name='行业类别')),
                ('area_level', models.CharField(max_length=10, verbose_name='区域等级')),
                ('agent', models.CharField(max_length=20, verbose_name='经办人')),
                ('pur_level', models.CharField(blank=True, max_length=10, null=True, verbose_name='采购级别')),
                ('pur_way', models.CharField(blank=True, max_length=10, null=True, verbose_name='采购途径')),
                ('distribution', models.BooleanField(verbose_name='分配情况')),
                ('check_status', models.CharField(max_length=10, verbose_name='审核状态')),
                ('org_category', models.CharField(max_length=10, verbose_name='机构类型')),
                ('follow_status', models.CharField(max_length=10, verbose_name='跟进状态')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('tag', models.CharField(blank=True, max_length=10, null=True, verbose_name='标签')),
                ('linkman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.Linkman', verbose_name='联系人')),
            ],
        ),
    ]
