# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-05 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=32, verbose_name='部门名称')),
                ('leader_title', models.CharField(max_length=32, verbose_name='领导职称')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=32, verbose_name='员工姓名')),
                ('staff_salary', models.FloatField(max_length=32, verbose_name='员工薪资')),
                ('staff_state', models.BooleanField(default=True, verbose_name='员工状态')),
                ('staff_job', models.CharField(max_length=32, verbose_name='职位名称')),
                ('staff_job_level', models.CharField(max_length=32, verbose_name='职务级别')),
                ('department', models.ManyToManyField(to='employee_management.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工信息id')),
            ],
        ),
    ]
